In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 1, 1, 1],
    [1, 1, 0, 0],
    [1, 0, 1, 1],
    [1, 0, 1, 1]
])
A

array([[1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 1]])

In [3]:
X = np.random.uniform(-1, 1, (4, 4))
X

array([[-0.93404023,  0.88168921,  0.58528596,  0.55452137],
       [-0.06177679, -0.60722957, -0.28568677,  0.60748628],
       [-0.04278492, -0.43494923,  0.28309164,  0.7140047 ],
       [ 0.29574681,  0.73385484, -0.13823721, -0.29907732]])

In [4]:
W = np.random.uniform(-1, 1, (2, 4))
W

array([[-0.74854751, -0.74141834,  0.73067398,  0.70217093],
       [-0.96673385,  0.97933429, -0.73798716, -0.7012416 ]])

In [5]:
W_att = np.random.uniform(-1, 1, (1, 4))
W_att

array([[ 0.48347146, -0.01182378,  0.1633881 , -0.62704387]])

In [6]:
connections = np.where(A > 0)
connections

(array([0, 0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 1, 0, 2, 3, 0, 2, 3]))

In [7]:
np.concatenate([(X @ W.T)[connections[0]], (X @ W.T)[connections[1]]], axis=1)

array([[ 0.86249495,  0.94564981,  0.86249495,  0.94564981],
       [ 0.86249495,  0.94564981,  0.71426932, -0.7501205 ],
       [ 0.86249495,  0.94564981,  1.06270691, -1.09420685],
       [ 0.86249495,  0.94564981, -1.07648371,  0.7445235 ],
       [ 0.71426932, -0.7501205 ,  0.86249495,  0.94564981],
       [ 0.71426932, -0.7501205 ,  0.71426932, -0.7501205 ],
       [ 1.06270691, -1.09420685,  0.86249495,  0.94564981],
       [ 1.06270691, -1.09420685,  1.06270691, -1.09420685],
       [ 1.06270691, -1.09420685, -1.07648371,  0.7445235 ],
       [-1.07648371,  0.7445235 ,  0.86249495,  0.94564981],
       [-1.07648371,  0.7445235 ,  1.06270691, -1.09420685],
       [-1.07648371,  0.7445235 , -1.07648371,  0.7445235 ]])

In [8]:
a = W_att @ np.concatenate([(X @ W.T)[connections[0]], (X @ W.T)[connections[1]]], axis=1).T
a

array([[-0.04623197,  0.99287211,  1.2655599 , -0.23692298, -0.09784441,
         0.94125966,  0.07468362,  1.38647549, -0.11600739, -0.98129474,
         0.33049713, -1.17198576]])

In [9]:
def leaky_relu(x, alpha=0.2):
    return np.maximum(alpha*x, x)

e = leaky_relu(a)
e

array([[-0.00924639,  0.99287211,  1.2655599 , -0.0473846 , -0.01956888,
         0.94125966,  0.07468362,  1.38647549, -0.02320148, -0.19625895,
         0.33049713, -0.23439715]])

In [10]:
E = np.zeros(A.shape)
E[connections[0], connections[1]] = e[0]
E

array([[-0.00924639,  0.99287211,  1.2655599 , -0.0473846 ],
       [-0.01956888,  0.94125966,  0.        ,  0.        ],
       [ 0.07468362,  0.        ,  1.38647549, -0.02320148],
       [-0.19625895,  0.        ,  0.33049713, -0.23439715]])

In [11]:
def softmax2D(x, axis):
    e = np.exp(x - np.expand_dims(np.max(x, axis=axis), axis))
    sum = np.expand_dims(np.sum(e, axis=axis), axis)
    return e / sum

W_alpha = softmax2D(E, 1)
W_alpha

array([[0.12099748, 0.32960278, 0.43292999, 0.11646974],
       [0.17688519, 0.46235335, 0.18038073, 0.18038073],
       [0.15272747, 0.14173675, 0.56704969, 0.1384861 ],
       [0.20521863, 0.24971864, 0.34752339, 0.19753933]])

In [12]:
H = A.T @ W_alpha @ X @ W.T
H

array([[ 2.35333563, -1.46814684],
       [ 1.15480712, -0.76244648],
       [ 1.8730133 , -1.22552142],
       [ 1.8730133 , -1.22552142]])